project:
  type: website
  output-dir: _site

website:
  title: "ISSS626 Geospatial Analytics"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "Hands-on Exercises"
        menu:
          - href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
            text: "Hands-on Ex01"
      - text: "In-class Exercises"
        menu:
          - href: In-class_Ex/In-class_Ex01/In-class_Ex01.qmd
            text: "In-class Ex01"
      - text: "Take-home Exercises"
        menu:
          - href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd
            text: "Take-home Ex01"
    right:
      - href: about.qmd
        text: About

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true

editor: visual


