---
title: "In-class Exercise 05: Local Measures of Spatial Autocorrelation"
author: "Meng Xinyu"
date: "`r Sys.Date()`"
date-modified: "last-modified"
format: html
execute:
  eval: true
  echo: true
  warning: false
  freeze: true
---

```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse)
```

```{r}
hunan <- st_read(dsn = "data/geospatial",
                 layer = "Hunan")
```

```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
hunan_GDPPC <- left_join(hunan, hunan2012) %>%
  select(1:4, 7, 15, 33)
```

```{r}
wm_q <- hunan_GDPPC %>%
  mutate(nb = st_contiguity(geometry),
         wt = st_weights(nb,
                         style = "W"),
         .before = 1)
```

```{r}
moranI <- global_moran(wm_q$GDPPC,
                       wm_q$nb,
                       wm_q$wt)
glimpse(moranI)
```

```{r}
global_moran_test(wm_q$GDPPC,
                  wm_q$nb,
                  wm_q$wt)
```

```{r}
set.seed(1234)

global_moran_perm(wm_q$GDPPC,
                  wm_q$nb,
                  wm_q$wt,
                  nsim = 99)
```

```{r}
lisa <- wm_q %>%
  mutate(local_moran = local_moran(
    GDPPC, nb, wt, nsim = 99),
         .before = 1) %>%
  unnest(local_moran)
```

```{r}
lisa_sig <- lisa %>%
  filter(p_ii_sim < 0.05)

tmap_mode("plot")
tm_shape(lisa) +
  tm_polygons() +
  tm_borders(fill_alpha = 0.5) +
tm_shape(lisa_sig) +
  tm_polygons(fill = "mean",
              fill.legend = tm_legend(
                text.size = 1.15,
                width = 6)) +
  tm_borders(fill_alpha = 0.4) +
  tm_layout(legend.title.size = 1.25)
```

```{r}
wm_idw <- hunan_GDPPC %>%
  mutate(nb = include_self(st_contiguity(geometry)),
         wts = st_inverse_distance(nb, geometry,
                                   scale = 1,
                                   alpha = 1),
         .before = 1)

HCSA <- wm_idw %>%
  mutate(local_Gi = local_gstar_perm(
    GDPPC, nb, wts, nsim = 99),
         .before = 1) %>%
  unnest(local_Gi)
```

```{r}
tmap_mode("plot")
tm_shape(HCSA) +
  tm_polygons(
    fill = "p_sim",
    fill.scale = tm_scale_intervals(
      breaks = c(0, 0.001, 0.01, 0.05, 1.0),
      labels = c("p < 0.001", "p < 0.01", "p < 0.05", "Not Significant"),
      values = c("#de2d26", "#fc9272", "#fee0d2", "#e0e0e0")),
    fill.legend = tm_legend(
      title = "p-values")
  ) +
  tm_title("p-values of G*i for GDP per capita") +
  tm_borders(fill_alpha = 0.5)
```

```{r}
tmap_mode("plot")
tm_shape(lisa) +
  tm_polygons(fill = "p_ii_sim") +
  tm_borders(fill_alpha = 0.5) +
  tm_title("p-value of local Moran's I") +
  tm_layout(legend.title.size = 1.5)
```
