<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Meng Xinyu">
<meta name="dcterms.date" content="2026-09-23">

<title>Take-home Exercise 1: Forest-fire Point Patterns in Central Kalimantan – ISSS626 Geospatial Analytics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-4eaa7e2902977deb636442ed8e0cf898.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626 Geospatial Analytics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Ex01</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Ex02</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Ex03</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Ex04</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html">
 <span class="dropdown-text">Hands-on Ex05</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex01/In-class_Ex01.qmd">
 <span class="dropdown-text">In-class Ex01</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-class Ex04</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Take-home Ex01 — Report</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01_Summary.html">
 <span class="dropdown-text">Take-home Ex01 — Summary</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">1</span> Overview</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions"><span class="header-section-number">2</span> Research questions</a></li>
  <li><a href="#data-and-study-design" id="toc-data-and-study-design" class="nav-link" data-scroll-target="#data-and-study-design"><span class="header-section-number">3</span> Data and study design</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources"><span class="header-section-number">3.1</span> Data sources</a></li>
  <li><a href="#point-event-definition" id="toc-point-event-definition" class="nav-link" data-scroll-target="#point-event-definition"><span class="header-section-number">3.2</span> Point event definition</a></li>
  <li><a href="#spatial-study-window" id="toc-spatial-study-window" class="nav-link" data-scroll-target="#spatial-study-window"><span class="header-section-number">3.3</span> Spatial study window</a></li>
  <li><a href="#temporal-study-window" id="toc-temporal-study-window" class="nav-link" data-scroll-target="#temporal-study-window"><span class="header-section-number">3.4</span> Temporal study window</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions"><span class="header-section-number">3.5</span> Assumptions</a></li>
  <li><a href="#methodological-choices" id="toc-methodological-choices" class="nav-link" data-scroll-target="#methodological-choices"><span class="header-section-number">3.6</span> Methodological choices</a></li>
  </ul></li>
  <li><a href="#installing-and-loading-r-packages" id="toc-installing-and-loading-r-packages" class="nav-link" data-scroll-target="#installing-and-loading-r-packages"><span class="header-section-number">4</span> Installing and loading R packages</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation"><span class="header-section-number">5</span> Data preparation</a>
  <ul class="collapse">
  <li><a href="#importing-the-study-area" id="toc-importing-the-study-area" class="nav-link" data-scroll-target="#importing-the-study-area"><span class="header-section-number">5.1</span> Importing the study area</a></li>
  <li><a href="#importing-and-combining-the-fire-detections" id="toc-importing-and-combining-the-fire-detections" class="nav-link" data-scroll-target="#importing-and-combining-the-fire-detections"><span class="header-section-number">5.2</span> Importing and combining the fire detections</a></li>
  <li><a href="#cleaning" id="toc-cleaning" class="nav-link" data-scroll-target="#cleaning"><span class="header-section-number">5.3</span> Cleaning</a></li>
  <li><a href="#converting-to-sf-and-clipping-to-the-regency" id="toc-converting-to-sf-and-clipping-to-the-regency" class="nav-link" data-scroll-target="#converting-to-sf-and-clipping-to-the-regency"><span class="header-section-number">5.4</span> Converting to sf and clipping to the regency</a></li>
  <li><a href="#removing-repeated-detections" id="toc-removing-repeated-detections" class="nav-link" data-scroll-target="#removing-repeated-detections"><span class="header-section-number">5.5</span> Removing repeated detections</a></li>
  <li><a href="#creating-the-spatstat-objects-ppp-and-owin" id="toc-creating-the-spatstat-objects-ppp-and-owin" class="nav-link" data-scroll-target="#creating-the-spatstat-objects-ppp-and-owin"><span class="header-section-number">5.6</span> Creating the spatstat objects (ppp and owin)</a></li>
  </ul></li>
  <li><a href="#first-order-analysis-intensity" id="toc-first-order-analysis-intensity" class="nav-link" data-scroll-target="#first-order-analysis-intensity"><span class="header-section-number">6</span> First-order analysis: intensity</a>
  <ul class="collapse">
  <li><a href="#clark-evans-test" id="toc-clark-evans-test" class="nav-link" data-scroll-target="#clark-evans-test"><span class="header-section-number">6.1</span> Clark-Evans test</a></li>
  <li><a href="#kernel-density-with-different-bandwidths" id="toc-kernel-density-with-different-bandwidths" class="nav-link" data-scroll-target="#kernel-density-with-different-bandwidths"><span class="header-section-number">6.2</span> Kernel density with different bandwidths</a></li>
  <li><a href="#adaptive-kde" id="toc-adaptive-kde" class="nav-link" data-scroll-target="#adaptive-kde"><span class="header-section-number">6.3</span> Adaptive KDE</a></li>
  <li><a href="#cartographic-quality-kde-map" id="toc-cartographic-quality-kde-map" class="nav-link" data-scroll-target="#cartographic-quality-kde-map"><span class="header-section-number">6.4</span> Cartographic-quality KDE map</a></li>
  </ul></li>
  <li><a href="#second-order-analysis-interaction" id="toc-second-order-analysis-interaction" class="nav-link" data-scroll-target="#second-order-analysis-interaction"><span class="header-section-number">7</span> Second-order analysis: interaction</a>
  <ul class="collapse">
  <li><a href="#g-function-nearest-neighbour-distances" id="toc-g-function-nearest-neighbour-distances" class="nav-link" data-scroll-target="#g-function-nearest-neighbour-distances"><span class="header-section-number">7.1</span> G-function (nearest-neighbour distances)</a></li>
  <li><a href="#f-function-empty-space-distances" id="toc-f-function-empty-space-distances" class="nav-link" data-scroll-target="#f-function-empty-space-distances"><span class="header-section-number">7.2</span> F-function (empty-space distances)</a></li>
  <li><a href="#k-function" id="toc-k-function" class="nav-link" data-scroll-target="#k-function"><span class="header-section-number">7.3</span> K-function</a></li>
  <li><a href="#l-function" id="toc-l-function" class="nav-link" data-scroll-target="#l-function"><span class="header-section-number">7.4</span> L-function</a></li>
  </ul></li>
  <li><a href="#value-added-1-inhomogeneous-l-function" id="toc-value-added-1-inhomogeneous-l-function" class="nav-link" data-scroll-target="#value-added-1-inhomogeneous-l-function"><span class="header-section-number">8</span> Value-added 1: inhomogeneous L-function</a></li>
  <li><a href="#value-added-2-spatio-temporal-kde-by-month" id="toc-value-added-2-spatio-temporal-kde-by-month" class="nav-link" data-scroll-target="#value-added-2-spatio-temporal-kde-by-month"><span class="header-section-number">9</span> Value-added 2: spatio-temporal KDE by month</a>
  <ul class="collapse">
  <li><a href="#building-the-marked-ppp" id="toc-building-the-marked-ppp" class="nav-link" data-scroll-target="#building-the-marked-ppp"><span class="header-section-number">9.1</span> Building the marked ppp</a></li>
  <li><a href="#computing-and-plotting-the-stkde" id="toc-computing-and-plotting-the-stkde" class="nav-link" data-scroll-target="#computing-and-plotting-the-stkde"><span class="header-section-number">9.2</span> Computing and plotting the STKDE</a></li>
  </ul></li>
  <li><a href="#integrated-findings-and-discussion" id="toc-integrated-findings-and-discussion" class="nav-link" data-scroll-target="#integrated-findings-and-discussion"><span class="header-section-number">10</span> Integrated findings and discussion</a></li>
  <li><a href="#implications-for-public-safety-planning" id="toc-implications-for-public-safety-planning" class="nav-link" data-scroll-target="#implications-for-public-safety-planning"><span class="header-section-number">11</span> Implications for public-safety planning</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">12</span> Limitations</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">13</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 1: Forest-fire Point Patterns in Central Kalimantan</h1>
<p class="subtitle lead">Spatial and spatio-temporal point pattern analysis of fire detections in Kabupaten Pulang Pisau, 2026</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Meng Xinyu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 23, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 26, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="overview" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Overview</h1>
<p>Peatland fires are a recurring public-safety problem in Central Kalimantan. Peat fires are hard to put out, they produce haze that spreads across the region, and they damage both health and the local economy. To support prevention and response, this exercise looks at the satellite fire record and asks two basic questions: where do fire detections concentrate, and are they really clustered or just densely scattered.</p>
<p>The study area is one regency, Kabupaten Pulang Pisau, and the data are VIIRS fire detections from 2026. Following the workflow taught in class (r4gdsa Chapters 4-6), the analysis separates first-order effects (how the intensity of detections varies across space) from second-order effects (whether detections interact - cluster, inhibit, or appear random). These two properties are measured with different tools, so they are reported separately.</p>
</section>
<section id="research-questions" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Research questions</h1>
<ol type="1">
<li>Where does fire-detection intensity concentrate within the regency, and how does it change over the observation period?</li>
<li>Are the detections significantly clustered compared with a Complete Spatial Randomness (CSR) baseline, rather than only appearing clustered on a map?</li>
<li>(Value-added) Does the high-intensity area move over the season, and does the clustering hold once the uneven intensity is accounted for?</li>
</ol>
</section>
<section id="data-and-study-design" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data and study design</h1>
<section id="data-sources" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="data-sources"><span class="header-section-number">3.1</span> Data sources</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Dataset</th>
<th>Source</th>
<th>Access date</th>
<th>Coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fire detections, VIIRS 375 m (NOAA-20 / VJ114)</td>
<td>NASA FIRMS, Archive Download</td>
<td>2026-09-23</td>
<td>Indonesia; 2026-01-01 to 2026-09-23</td>
</tr>
<tr class="even">
<td>Regency boundaries (ADM2)</td>
<td>GADM v4.1</td>
<td>2026-09-23</td>
<td>Indonesia, regency level</td>
</tr>
</tbody>
</table>
<p>FIRMS returned the export as two files: a standard (science-quality) file for the earlier part of the year and a near-real-time (NRT) file for the recent months that have not been reprocessed yet. Both are read and combined, and a <code>source</code> column is kept so the standard/NRT split can be reported.</p>
</section>
<section id="point-event-definition" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="point-event-definition"><span class="header-section-number">3.2</span> Point event definition</h2>
<p>A point event is one VIIRS fire detection - a single 375 m pixel flagged as an active fire at one satellite overpass, placed at the pixel centroid.</p>
<p>One point to be clear about early: a detection is not a distinct fire. A fire that burns for several days is picked up on several overpasses, so the raw file contains the same fire many times. This inflates apparent clustering, so repeated detections are reduced to one point per pixel per day before analysis.</p>
<p>The remaining cleaning steps are routine: drop exact duplicate rows, remove records with missing or impossible coordinates, drop low-confidence detections, and keep only records inside the regency and inside the observation window.</p>
</section>
<section id="spatial-study-window" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="spatial-study-window"><span class="header-section-number">3.3</span> Spatial study window</h2>
<p>The analysis is confined to Kabupaten Pulang Pisau. A single regency is used because it is an administrative unit (so a finding maps onto who would plan or respond), it is dominated by peatland (so the fires belong to a fairly consistent regime), and one regency keeps the point pattern small enough for the distance-based tests. The regency polygon becomes the observation window (<code>owin</code>) for all spatstat steps, so intensity estimates and edge corrections respect the true boundary.</p>
</section>
<section id="temporal-study-window" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="temporal-study-window"><span class="header-section-number">3.4</span> Temporal study window</h2>
<p>The data cover 1 January 2026 to 23 September 2026, the full range available at download. Because 2026 is not over, this is a partial year: it captures the build-up of the dry season but not its later peak around October-November, so seasonal readings are incomplete.</p>
</section>
<section id="assumptions" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="assumptions"><span class="header-section-number">3.5</span> Assumptions</h2>
<p>KDE assumes a smooth underlying intensity surface, and the result depends heavily on the bandwidth, so more than one bandwidth is shown. The K and L functions compare the pattern against a homogeneous Poisson process (constant intensity everywhere). That assumption is almost certainly false here, because fire intensity is driven by where the peatland is, so a homogeneous test can read first-order heterogeneity as clustering. To separate the two, an inhomogeneous L is added as a value-added check. The tests also assume detections are independent, which is exactly what repeated detections break - hence the de-duplication.</p>
</section>
<section id="methodological-choices" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="methodological-choices"><span class="header-section-number">3.6</span> Methodological choices</h2>
<p>The projected CRS is EPSG:32749 (UTM zone 49S), which covers Central Kalimantan and gives distances in metres; values are rescaled to kilometres for readability. KDE uses two data-driven bandwidths (<code>bw.diggle</code>, <code>bw.ppl</code>), a fixed bandwidth, and an adaptive estimate. Second-order tests use Ripley’s edge correction and are assessed against Monte Carlo envelopes.</p>
</section>
</section>
<section id="installing-and-loading-r-packages" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Installing and loading R packages</h1>
<p>Following Chapters 4-6, the packages used are sf, spatstat, sparr, terra, tmap and tidyverse.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, spatstat, sparr, terra, tmap, tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="data-preparation" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Data preparation</h1>
<section id="importing-the-study-area" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="importing-the-study-area"><span class="header-section-number">5.1</span> Importing the study area</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>idn_adm2 <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/raw"</span>, <span class="at">layer =</span> <span class="st">"gadm41_IDN_2"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `gadm41_IDN_2' from data source 
  `/Users/mengxinyu/ISSS626-GAA/Take-home_Ex/Take-home_Ex01/data/raw' 
  using driver `ESRI Shapefile'
Simple feature collection with 502 features and 13 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 95.00971 ymin: -11.00761 xmax: 141.0194 ymax: 6.076941
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>study_area <span class="ot">&lt;-</span> idn_adm2 <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(NAME_2 <span class="sc">==</span> <span class="st">"Pulang Pisau"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32749</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(<span class="fu">st_is_valid</span>(study_area))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(study_area) <span class="sc">+</span> <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Study area: Kabupaten Pulang Pisau"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/plot-boundary-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="importing-and-combining-the-fire-detections" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="importing-and-combining-the-fire-detections"><span class="header-section-number">5.2</span> Importing and combining the fire detections</h2>
<p>The two files disagree on a few column types (for example <code>version</code> is numeric in the standard file and text in the NRT file), so everything is read as text first, stacked, then <code>type_convert()</code> decides the types on the combined table.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>fire_archive <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/raw/fire_archive_J1V-C2_811410.csv"</span>,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">col_types =</span> <span class="fu">cols</span>(<span class="at">.default =</span> <span class="fu">col_character</span>()))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>fire_nrt     <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/raw/fire_nrt_J1V-C2_811410.csv"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">col_types =</span> <span class="fu">cols</span>(<span class="at">.default =</span> <span class="fu">col_character</span>()))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>fire_raw <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="at">archive =</span> fire_archive, <span class="at">nrt =</span> fire_nrt, <span class="at">.id =</span> <span class="st">"source"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">type_convert</span>()</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(fire_raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 370,354
Columns: 16
$ source     &lt;chr&gt; "archive", "archive", "archive", "archive", "archive", "arc…
$ latitude   &lt;dbl&gt; -6.32139, -2.73144, -2.74199, -2.72553, -2.73672, -2.74262,…
$ longitude  &lt;dbl&gt; 138.6728, 132.9328, 132.9431, 132.9320, 132.9379, 132.9388,…
$ brightness &lt;dbl&gt; 342.70, 351.49, 354.93, 333.18, 356.28, 355.71, 355.96, 331…
$ scan       &lt;dbl&gt; 0.43, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.39, 0.46, 0.56,…
$ track      &lt;dbl&gt; 0.46, 0.65, 0.64, 0.65, 0.65, 0.65, 0.65, 0.36, 0.39, 0.43,…
$ acq_date   &lt;date&gt; 2026-01-01, 2026-01-01, 2026-01-01, 2026-01-01, 2026-01-01…
$ acq_time   &lt;chr&gt; "0352", "0353", "0353", "0353", "0353", "0353", "0353", "05…
$ satellite  &lt;chr&gt; "N20", "N20", "N20", "N20", "N20", "N20", "N20", "N20", "N2…
$ instrument &lt;chr&gt; "VIIRS", "VIIRS", "VIIRS", "VIIRS", "VIIRS", "VIIRS", "VIIR…
$ confidence &lt;chr&gt; "n", "n", "n", "n", "l", "n", "l", "n", "n", "n", "n", "n",…
$ version    &lt;chr&gt; "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2",…
$ bright_t31 &lt;dbl&gt; 286.85, 288.75, 289.22, 288.10, 289.07, 288.19, 287.82, 295…
$ frp        &lt;dbl&gt; 7.55, 14.95, 46.30, 6.35, 14.95, 23.54, 14.95, 1.16, 4.11, …
$ daynight   &lt;chr&gt; "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D",…
$ type       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 3, 1, 1,…</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>fire_raw <span class="sc">%&gt;%</span> <span class="fu">count</span>(source)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  source       n
  &lt;chr&gt;    &lt;int&gt;
1 archive  35153
2 nrt     335201</code></pre>
</div>
</div>
</section>
<section id="cleaning" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="cleaning"><span class="header-section-number">5.3</span> Cleaning</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>fire_clean <span class="ot">&lt;-</span> fire_raw <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(latitude), <span class="sc">!</span><span class="fu">is.na</span>(longitude),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>         <span class="fu">between</span>(latitude, <span class="sc">-</span><span class="dv">90</span>, <span class="dv">90</span>), <span class="fu">between</span>(longitude, <span class="sc">-</span><span class="dv">180</span>, <span class="dv">180</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(confidence <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"n"</span>, <span class="st">"h"</span>)) <span class="sc">%&gt;%</span>          <span class="co"># VIIRS: keep nominal + high</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">acq_date =</span> <span class="fu">as.Date</span>(acq_date)) <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(acq_date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2026-01-01"</span>),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>         acq_date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2026-09-23"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Month_num =</span> <span class="fu">month</span>(acq_date),</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">Month_fac =</span> <span class="fu">month</span>(acq_date, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>))</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(fire_raw); <span class="fu">nrow</span>(fire_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 370354</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 351822</code></pre>
</div>
</div>
<p>Cleaning drops the national record from 370,354 to 351,822 (removing missing/invalid coordinates and low-confidence detections). Clipping to Pulang Pisau in the next step leaves 16,189 detections.</p>
</section>
<section id="converting-to-sf-and-clipping-to-the-regency" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="converting-to-sf-and-clipping-to-the-regency"><span class="header-section-number">5.4</span> Converting to sf and clipping to the regency</h2>
<p>Following Chapter 1, the aspatial csv is converted with <code>st_as_sf()</code> and transformed to the projected CRS. Clipping to the regency is done right after, because running anything on the whole-Indonesia file first causes a memory blow-up.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fire_sf <span class="ot">&lt;-</span> fire_clean <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32749</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_intersection</span>(study_area)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(fire_sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16189</code></pre>
</div>
</div>
</section>
<section id="removing-repeated-detections" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="removing-repeated-detections"><span class="header-section-number">5.5</span> Removing repeated detections</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>fire_dedup <span class="ot">&lt;-</span> fire_sf <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">x =</span> <span class="fu">st_coordinates</span>(.)[, <span class="dv">1</span>],</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="fu">st_coordinates</span>(.)[, <span class="dv">2</span>]) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(x, y, acq_date, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(fire_sf); <span class="fu">nrow</span>(fire_dedup)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16189</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16189</code></pre>
</div>
</div>
<p>Here the per-pixel-per-day rule removes no rows, which means the export contained no exact same-day repeats at identical coordinates.</p>
</section>
<section id="creating-the-spatstat-objects-ppp-and-owin" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="creating-the-spatstat-objects-ppp-and-owin"><span class="header-section-number">5.6</span> Creating the spatstat objects (ppp and owin)</h2>
<p>Following Chapter 4, <code>as.ppp()</code> converts the points and <code>as.owin()</code> builds the observation window; the two are then combined and rescaled to kilometres.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>fire_ppp <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(<span class="fu">st_geometry</span>(fire_dedup))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>fire_owin <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(study_area)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">Window</span>(fire_ppp) <span class="ot">&lt;-</span> fire_owin</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># check for coincident points (spatstat needs no exact duplicates)</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">multiplicity</span>(fire_ppp) <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>fire_ppp <span class="ot">&lt;-</span> <span class="fu">rjitter</span>(fire_ppp, <span class="at">retry =</span> <span class="cn">TRUE</span>, <span class="at">nsim =</span> <span class="dv">1</span>, <span class="at">drop =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>fire_ppp.km <span class="ot">&lt;-</span> <span class="fu">rescale.ppp</span>(fire_ppp, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fire_ppp.km)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  16189 points
Average intensity 1.661998 points per square km

Coordinates are given to 13 decimal places

Window: polygonal boundary
single connected closed polygon with 843 vertices
enclosing rectangle: [786.3871, 870.7875] x [9616.111, 9829.378] km
                     (84.4 x 213.3 km)
Window area = 9740.69 square km
Unit of length: 1 km
Fraction of frame area: 0.541</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fire_ppp.km, <span class="at">main =</span> <span class="st">"Fire detections after cleaning"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/plot-ppp-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Because the pattern has 16,189 points, the Monte Carlo envelopes in the second-order section become very slow. Following the standard practice of testing CSR on a subsample, a reproducible random sample of 3,000 points is drawn and used for the envelope tests only (the first-order KDE below uses all points).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>fire_sub <span class="ot">&lt;-</span> fire_ppp.km[<span class="fu">sample</span>(fire_ppp.km<span class="sc">$</span>n, <span class="dv">3000</span>)]</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>fire_sub</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern: 3000 points
window: polygonal boundary
enclosing rectangle: [786.3871, 870.7875] x [9616.111, 9829.378] km</code></pre>
</div>
</div>
</section>
</section>
<section id="first-order-analysis-intensity" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> First-order analysis: intensity</h1>
<section id="clark-evans-test" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="clark-evans-test"><span class="header-section-number">6.1</span> Clark-Evans test</h2>
<p>Following Chapter 4, the Clark-Evans test is used first to check whether the pattern is clustered, random, or regular. The Clark-Evans index R is below 1 for clustering and above 1 for regularity.</p>
<ul>
<li>H0: the detections are randomly distributed.</li>
<li>H1: the detections are not randomly distributed.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">clarkevans.test</span>(fire_ppp.km, <span class="at">correction =</span> <span class="st">"none"</span>,</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">clipregion =</span> fire_owin,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">alternative =</span> <span class="st">"clustered"</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">method =</span> <span class="st">"MonteCarlo"</span>, <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Clark-Evans test
    No edge correction
    Monte Carlo test based on 99 simulations of CSR with fixed n

data:  fire_ppp.km
R = 0.41914, p-value = 0.01
alternative hypothesis: clustered (R &lt; 1)</code></pre>
</div>
</div>
<p>The Monte Carlo Clark-Evans test gives R well below 1 with a very small p-value, so the null of random distribution is rejected: the detections are clustered. This is a first-order signal - it tells us the pattern is not random, and the KDE below shows where the intensity is highest.</p>
</section>
<section id="kernel-density-with-different-bandwidths" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="kernel-density-with-different-bandwidths"><span class="header-section-number">6.2</span> Kernel density with different bandwidths</h2>
<p>Following Chapter 4, KDE is computed with <code>density()</code> using two automatic bandwidths and one fixed value, all with a Gaussian kernel and edge correction.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>kde_diggle <span class="ot">&lt;-</span> <span class="fu">density</span>(fire_ppp.km, <span class="at">sigma =</span> bw.diggle, <span class="at">edge =</span> <span class="cn">TRUE</span>, <span class="at">kernel =</span> <span class="st">"gaussian"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>kde_ppl    <span class="ot">&lt;-</span> <span class="fu">density</span>(fire_ppp.km, <span class="at">sigma =</span> bw.ppl,    <span class="at">edge =</span> <span class="cn">TRUE</span>, <span class="at">kernel =</span> <span class="st">"gaussian"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>kde_fixed  <span class="ot">&lt;-</span> <span class="fu">density</span>(fire_ppp.km, <span class="at">sigma =</span> <span class="dv">2</span>,         <span class="at">edge =</span> <span class="cn">TRUE</span>, <span class="at">kernel =</span> <span class="st">"gaussian"</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>))</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_diggle, <span class="at">main =</span> <span class="st">"bw.diggle"</span>)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_ppl,    <span class="at">main =</span> <span class="st">"bw.ppl"</span>)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_fixed,  <span class="at">main =</span> <span class="st">"fixed 2 km"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/kde-bw-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="adaptive-kde" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="adaptive-kde"><span class="header-section-number">6.3</span> Adaptive KDE</h2>
<p>Following Chapter 4.8, an adaptive-bandwidth KDE is added, which is less sensitive to the uneven spread of points than a fixed bandwidth.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>kde_adaptive <span class="ot">&lt;-</span> <span class="fu">adaptive.density</span>(fire_ppp.km, <span class="at">method =</span> <span class="st">"kernel"</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_adaptive, <span class="at">main =</span> <span class="st">"Adaptive KDE"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/kde-adaptive-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="cartographic-quality-kde-map" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="cartographic-quality-kde-map"><span class="header-section-number">6.4</span> Cartographic-quality KDE map</h2>
<p>Following Chapter 4.9, the <code>im</code> output is converted to a SpatRaster with <code>terra::rast()</code>, the CRS is assigned, and the map is drawn with tmap.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>kde_terra <span class="ot">&lt;-</span> <span class="fu">rast</span>(kde_ppl)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">crs</span>(kde_terra) <span class="ot">&lt;-</span> <span class="st">"EPSG:32749"</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(kde_terra) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(<span class="at">palette =</span> <span class="st">"YlOrRd"</span>, <span class="at">title =</span> <span class="st">"Intensity"</span>) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(study_area) <span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"grey30"</span>) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Fire-detection intensity"</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/kde-tmap-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The KDE shows detections concentrated in the central and southern parts of the regency, with little activity in the north. The same hotspot shows up under all three bandwidths, so the location of the peak does not depend on the smoothing choice (the smaller bandwidths just show more local detail). This southern concentration matches the low-lying peatland that dominates that part of Pulang Pisau and burns easily in the dry season. The map shows where intensity is high, not why - it reflects where detections happen, which depends on both fire activity and what the satellite could observe.</p>
</section>
</section>
<section id="second-order-analysis-interaction" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Second-order analysis: interaction</h1>
<p>The four functions below all test the same idea - are detections closer together than random - from different angles, so they are run together and read as a set. Each test uses the 3,000-point subsample and <code>envelope()</code> with <code>rank = 1, glocal = TRUE</code> as in Chapter 5.</p>
<p>For each test:</p>
<ul>
<li>H0: the detections are randomly distributed (CSR).</li>
<li>H1: the detections are not randomly distributed.</li>
<li>The null is rejected if the observed curve leaves the simulation envelope.</li>
</ul>
<section id="g-function-nearest-neighbour-distances" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="g-function-nearest-neighbour-distances"><span class="header-section-number">7.1</span> G-function (nearest-neighbour distances)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>G_csr <span class="ot">&lt;-</span> <span class="fu">envelope</span>(fire_sub, Gest, <span class="at">nsim =</span> <span class="dv">19</span>, <span class="at">rank =</span> <span class="dv">1</span>, <span class="at">glocal =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generating 19 simulated realisations of CSR  ...
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 
19.

Done.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(G_csr, <span class="at">main =</span> <span class="st">"G-function vs CSR envelope"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/gest-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The observed G rises above the envelope, meaning nearest-neighbour distances are shorter than expected under CSR - a sign of clustering.</p>
</section>
<section id="f-function-empty-space-distances" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="f-function-empty-space-distances"><span class="header-section-number">7.2</span> F-function (empty-space distances)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>F_csr <span class="ot">&lt;-</span> <span class="fu">envelope</span>(fire_sub, Fest, <span class="at">nsim =</span> <span class="dv">19</span>, <span class="at">rank =</span> <span class="dv">1</span>, <span class="at">glocal =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generating 19 simulated realisations of CSR  ...
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 
19.

Done.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(F_csr, <span class="at">main =</span> <span class="st">"F-function vs CSR envelope"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/fest-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The observed F sits below the envelope, meaning there is more empty space than expected under CSR - again consistent with clustering.</p>
</section>
<section id="k-function" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="k-function"><span class="header-section-number">7.3</span> K-function</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>K_csr <span class="ot">&lt;-</span> <span class="fu">envelope</span>(fire_sub, Kest, <span class="at">nsim =</span> <span class="dv">19</span>, <span class="at">rank =</span> <span class="dv">1</span>, <span class="at">glocal =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generating 19 simulated realisations of CSR  ...
1, 2,  [5:52 remaining] 3,
 [5:34 remaining] 4,  [5:11 remaining] 5,  [4:57 remaining] 6,
 [4:37 remaining] 7,  [4:17 remaining] 8,  [3:56 remaining] 9,
 [3:35 remaining] 10,  [3:12 remaining] 11,  [2:51 remaining] 12,
 [2:30 remaining] 13,  [2:08 remaining] 14,  [1:48 remaining] 15,
 [1:27 remaining] 16,  [1:05 remaining] 17,  [43 sec remaining] 18,
 [22 sec remaining] 
19.

Done.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(K_csr, . <span class="sc">-</span> r <span class="sc">~</span> r, <span class="at">xlab =</span> <span class="st">"d (km)"</span>, <span class="at">ylab =</span> <span class="st">"K(d)-r"</span>, <span class="at">main =</span> <span class="st">"K-function vs CSR envelope"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/kest-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="l-function" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="l-function"><span class="header-section-number">7.4</span> L-function</h2>
<p>The L-function is the clearest of the four because it shows clustering as a function of distance. It is plotted centred, so the CSR baseline is the horizontal line and any curve above it means clustering at that distance.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>L_csr <span class="ot">&lt;-</span> <span class="fu">envelope</span>(fire_sub, Lest, <span class="at">nsim =</span> <span class="dv">19</span>, <span class="at">rank =</span> <span class="dv">1</span>, <span class="at">glocal =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generating 19 simulated realisations of CSR  ...
1, 2,  [6:18 remaining] 3,
 [5:48 remaining] 4,  [5:21 remaining] 5,  [4:56 remaining] 6,
 [4:35 remaining] 7,  [4:17 remaining] 8,  [3:55 remaining] 9,
 [3:34 remaining] 10,  [3:13 remaining] 11,  [2:51 remaining] 12,
 [2:30 remaining] 13,  [2:09 remaining] 14,  [1:47 remaining] 15,
 [1:26 remaining] 16,  [1:05 remaining] 17,  [43 sec remaining] 18,
 [22 sec remaining] 
19.

Done.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(L_csr, . <span class="sc">-</span> r <span class="sc">~</span> r, <span class="at">xlab =</span> <span class="st">"d (km)"</span>, <span class="at">ylab =</span> <span class="st">"L(d)-r"</span>, <span class="at">main =</span> <span class="st">"L-function vs CSR envelope"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/lest-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The observed L is far above the envelope across the whole distance range up to about 20 km. So the detections are significantly more clustered than CSR at every scale, which is the expected pattern for fires concentrated in a few active areas rather than spread out independently. Together, G, F, K and L all point the same way: clear clustering.</p>
</section>
</section>
<section id="value-added-1-inhomogeneous-l-function" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Value-added 1: inhomogeneous L-function</h1>
<p>This part goes beyond the class methods. The CSR tests above assume intensity is constant, which it is not, so some of the “clustering” they show may just be the hotspots. The inhomogeneous L (<code>Linhom</code>) lets intensity vary and asks whether clustering still remains on top of that.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>Linhom_csr <span class="ot">&lt;-</span> <span class="fu">envelope</span>(fire_sub, Linhom, <span class="at">sigma =</span> bw.ppl,</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">nsim =</span> <span class="dv">19</span>, <span class="at">rank =</span> <span class="dv">1</span>, <span class="at">glocal =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generating 19 simulated realisations of CSR  ...
1, 2,  [6:29 remaining] 3,
 [6:09 remaining] 4,  [5:33 remaining] 5,  [5:12 remaining] 6,
 [4:50 remaining] 7,  [4:29 remaining] 8,  [4:08 remaining] 9,
 [3:48 remaining] 10,  [3:24 remaining] 11,  [3:02 remaining] 12,
 [2:39 remaining] 13,  [2:16 remaining] 14,  [1:53 remaining] 15,
 [1:30 remaining] 16,  [1:08 remaining] 17,  [45 sec remaining] 18,
 [23 sec remaining] 
19.

Done.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Linhom_csr, . <span class="sc">-</span> r <span class="sc">~</span> r, <span class="at">xlab =</span> <span class="st">"d (km)"</span>, <span class="at">ylab =</span> <span class="st">"Linhom(d)-r"</span>,</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Inhomogeneous L-function"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/linhom-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Once intensity is allowed to vary, the observed curve drops back close to the baseline for most distances instead of sitting far above it. This is the key result: after the hotspots are accounted for, little extra clustering is left, so the strong clustering in the homogeneous L is mostly explained by first-order heterogeneity (the uneven intensity), not by extra interaction between fires. The sharp rise at the largest distance is an edge effect and should not be over-read.</p>
</section>
<section id="value-added-2-spatio-temporal-kde-by-month" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Value-added 2: spatio-temporal KDE by month</h1>
<p>Following Chapter 6, the STKDE uses the month number as the temporal mark, then <code>spattemp.density()</code> of sparr estimates the density over space and time. This shows whether the busy areas move from month to month rather than staying put.</p>
<section id="building-the-marked-ppp" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="building-the-marked-ppp"><span class="header-section-number">9.1</span> Building the marked ppp</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>fire_month <span class="ot">&lt;-</span> fire_dedup <span class="sc">%&gt;%</span> <span class="fu">select</span>(Month_num)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>fire_month_ppp <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(fire_month)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>fire_month_owin <span class="ot">&lt;-</span> fire_month_ppp[fire_owin]</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fire_month_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern:  16189 points
Average intensity 1.661998e-06 points per square unit

*Pattern contains duplicated points*

Coordinates are given to 10 decimal places

marks are numeric, of type 'double'
Summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   9.000   9.000   8.781   9.000   9.000 

Window: polygonal boundary
single connected closed polygon with 843 vertices
enclosing rectangle: [786387.1, 870787.5] x [9616111, 9829378] units
                     (84400 x 213300 units)
Window area = 9740690000 square units
Fraction of frame area: 0.541</code></pre>
</div>
</div>
</section>
<section id="computing-and-plotting-the-stkde" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="computing-and-plotting-the-stkde"><span class="header-section-number">9.2</span> Computing and plotting the STKDE</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>st_kde <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(fire_month_owin, <span class="at">lambda =</span> <span class="fl">1.5</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(st_kde)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 6421.054 (spatial)
  lambda = 1.5 (temporal)

No. of observations
  16189 

Spatial bound
  Type: polygonal
  2D enclosure: [786387.1, 870787.5] x [9616111, 9829378]

Temporal bound
  [1, 9]

Evaluation
  128 x 128 x 9 trivariate lattice
  Density range: [2.620588e-23, 2.68829e-10]</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>tims <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> tims) {</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(st_kde, i, <span class="at">override.par =</span> <span class="cn">FALSE</span>, <span class="at">fix.range =</span> <span class="cn">TRUE</span>,</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"STKDE, month"</span>, i))</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/stkde-plot-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The monthly STKDE shows fire activity building up as the dry season advances rather than being spread evenly through the year. The high-density area stays broadly in the central-south peatland across the months rather than moving far, but it gets stronger over time. This adds a temporal side to the static KDE: the same core is at risk throughout, but the risk window is concentrated in a few months, so timing matters as much as location.</p>
</section>
</section>
<section id="integrated-findings-and-discussion" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Integrated findings and discussion</h1>
<p>The first-order and second-order results agree. The Clark-Evans test and the KDE show intensity is strongly uneven and concentrated in the central-south peatland. The G, F, K and L functions all confirm the detections are far more clustered than CSR. But the inhomogeneous L shows this clustering mainly reflects the uneven intensity rather than independent interaction between fires - fires are concentrated because the conditions for fire are concentrated. The monthly STKDE adds that this concentration also peaks in time, during the dry season.</p>
<p>As a robustness check, the hotspot location is stable across the three KDE bandwidths, and the homogeneous-vs-inhomogeneous L comparison shows the clustering signal is driven by first-order heterogeneity rather than one modelling choice. Alternative explanations still remain: repeated detections of the same fire, cloud cover and overpass timing, and the fact that detection intensity is not the same as risk to people or assets.</p>
</section>
<section id="implications-for-public-safety-planning" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Implications for public-safety planning</h1>
<p>The results support a targeted rather than uniform approach to fire management in Pulang Pisau. Because detections concentrate in the central and southern peatland, monitoring, patrols and early-response resources can be focused there instead of spread evenly. Because activity peaks in the dry-season months, readiness can be raised ahead of that window and lowered afterwards, which uses limited resources better. The hotspot staying in the same peatland also makes that landscape the priority for longer-term measures such as maintaining water levels and canal blocking, which reduce peat flammability.</p>
<p>Two limits matter. The analysis shows where and when detections concentrate, not why any fire started. And a concentration of detections is not the same as risk to people: turning these patterns into risk would need data on population, settlements and land use around the hotspot. So the findings are best used to focus attention and resources, not to draw causal conclusions.</p>
</section>
<section id="limitations" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Limitations</h1>
<p>Detections are not fires, and some repeated counting may remain even after de-duplication. Cloud cover and overpass timing leave gaps in what the satellite could see, so absence in the record is not the same as absence of fire. A concentration of detections is not by itself a measure of risk without knowing who and what is exposed. The observation window stops in September, so the later dry-season peak is missing. Finally, the CSR and KDE assumptions only partly hold, which is why the results are read against more than one baseline.</p>
</section>
<section id="references" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> References</h1>
<ul>
<li>R Core Team (2026). <em>R: A Language and Environment for Statistical Computing</em>.</li>
<li>Baddeley, A., Rubak, E., &amp; Turner, R. (2015). <em>Spatial Point Patterns: Methodology and Applications with R</em>. CRC Press.</li>
<li>Davies, T.M., Marshall, J.C., &amp; Hazelton, M.L. (2018). <em>sparr: Spatial and Spatiotemporal Relative Risk</em>. R package.</li>
<li>Kam, T.S. <em>R for Geospatial Data Science and Analysis</em> (r4gdsa), Chapters 4-6.</li>
<li>NASA FIRMS (VIIRS 375 m active-fire product); GADM v4.1.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>